// <auto-generated />
using System;
using DiscordJunkDrawer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiscordJunkDrawer.Migrations
{
    [DbContext(typeof(storageContext))]
    [Migration("20200506015128_idTypeChange")]
    partial class idTypeChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("DiscordJunkDrawer.Models.DiscordGuildModel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiscordGuilds");
                });

            modelBuilder.Entity("DiscordJunkDrawer.Models.DiscordRoleModel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("DiscordGuildModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ServerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscordGuildModelId");

                    b.ToTable("DiscordRoles");
                });

            modelBuilder.Entity("DiscordJunkDrawer.Models.DiscordRoleModel", b =>
                {
                    b.HasOne("DiscordJunkDrawer.Models.DiscordGuildModel", null)
                        .WithMany("Roles")
                        .HasForeignKey("DiscordGuildModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
